# Generated by Django 3.2.9 on 2021-12-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_seller_published_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='published_ads',
            field=models.IntegerField(default=9),
        ),
    ]
