# Generated by Django 3.2.9 on 2021-12-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_seller_published_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seller',
            name='published_ads',
            field=models.IntegerField(),
        ),
    ]
