# Generated by Django 3.2.9 on 2021-12-18 17:51

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211212_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveAds',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.ad',),
            managers=[
                ('archive', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='seller',
            name='published_ads',
        ),
    ]
