# Generated by Django 3.2.9 on 2021-12-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211218_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='itn',
            field=models.CharField(default=0, max_length=12),
        ),
    ]
