# Generated by Django 3.2.9 on 2022-01-07 17:40

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_seller_itn'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='world.png', upload_to=''),
        ),
    ]
