# Generated by Django 3.2.9 on 2022-01-07 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_seller_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='image',
        ),
    ]
