# Generated by Django 3.2.9 on 2022-01-11 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='seller',
            new_name='ad',
        ),
    ]
