# Generated by Django 3.2.9 on 2022-01-21 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
