# Generated by Django 3.2.9 on 2022-01-21 21:02

from django.db import migrations
from django.contrib.auth.management import create_permissions


def add_group_permissions(apps, schema_editor):

    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None

    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    common_group, created = Group.objects.get_or_create(name='Common group')
    banned_group, created = Group.objects.get_or_create(name='Banned group')

    create_ad = Permission.objects.get(codename='create_ads')

    if created:
        common_group.permissions.add(create_ad)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_delete_user'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions),
    ]
