# Generated by Django 3.2.9 on 2022-01-22 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20220122_0002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'permissions': (('create_ads', 'Can create new ads'), ('view_ads', 'Can view ads'))},
        ),
    ]
