# Generated by Django 3.2.9 on 2022-01-22 22:29

from django.db import migrations
from django.contrib.auth.management import create_permissions


def add_group_permissions(apps, schema_editor):

    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None

    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    banned_group, created = Group.objects.get_or_create(name='Banned group')

    view_ad = Permission.objects.get(codename='view_ads')

    if created:
        banned_group.permissions.add(view_ad)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_ad_options'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions),
    ]
