# Generated by Django 3.2.9 on 2022-02-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_smslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
