# Generated by Django 3.2.9 on 2022-10-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_seller_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='code',
            field=models.CharField(max_length=4),
        ),
    ]
